spring:
  application:
    name: bi_bakend
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finedb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
#mybatis-plus:
#  configuration:
#    # MyBatis ??
#    map-underscore-to-camel-case: true
#  global-config:
#    # ????
#    db-config:
#      # ?????
#      id-type: auto